import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-mono antialiased bg-teal-800"
        style={{
          backgroundColor: "rgb(17, 94, 89)",
          background: "radial-gradient(circle at bottom right, rgba(150, 56, 53, 1) 10%, rgba(17, 94, 89, 1) 65%)",
        }}
      >
        {children}
      </body>
    </html >
  );
}
